blog/accounts/urls.py
from django.conf.urls import url, include
from .views import profile, profile_edit

urlpatterns = [

    # login, logout, ecc. are already defined by Django

    # profile
    url(r'^profile/$', profile, name='profile'),
    url(r'^profile/edit$', profile_edit, name='profile_edit'),

    # registration, activation
    url(r'^', include('registration.backends.hmac.urls')),

]

blog/blog/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.core.urlresolvers import reverse_lazy

urlpatterns = [

    # home
    url(r'^$', RedirectView.as_view(url=reverse_lazy('posts:index')), name='index'),

    # posts app
    url(r'^posts/', include('posts.urls', namespace='posts')),

    # accounts (login etc)
    url(r'^accounts/', include('accounts.urls')),

    # admin panel
    url(r'^admin/', admin.site.urls),

]

blog/posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

    # posts list
    url(r'^$', views.index, name='index'),

    # new post
    url(r'^new$', views.add_post, name='new'),
]

blog/posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    creation_date = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=100)
    text = models.TextField(max_length=500)
    user = models.ForeignKey(User)

    # useful for the administration panel
    def __str__(self):
        return self.title

blog/accounts/forms.py
from django import forms
from django.contrib.auth.models import User


# form to modify user's profile
class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name", "last_name"]

blog/posts/forms.py
from django import forms
from .models import Post


# new post form
class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["title", "text"]

blog/accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.decorators import login_required
from .forms import ProfileEditForm


# render the profile page
@login_required
def profile(request):
    return render(request, 'accounts/profile.html')


# render the profile edit form
@login_required
def profile_edit(request):
    form = ProfileEditForm(request.POST or None, instance=request.user)

    if form.is_valid():
        form.save()
        return redirect('profile')

    return render(request, 'accounts/profile_edit.html', {'form': form})

blog/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render
from .models import Post
from .forms import AddPostForm


# posts list -> return all post in reverse chronological order
def index(request):
    posts = Post.objects.order_by('-creation_date')
    return render(request, 'posts/index.html', {'posts': posts})


# add a new post
@login_required
def add_post(request):
    form = AddPostForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        return redirect('posts:index')

    return render(request, 'posts/new.html', {'form': form})

blog/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}
    Profile | {{ block.super }}
{% endblock %}

{% block header %}
    Profile
{% endblock %}

{% block content %}
    <table class="table table-striped table-bordered">
        <tr>
            <th>Name</th>
            <td>{{ user.first_name }} {{ user.last_name }}</td>
        </tr>
        <tr>
            <th>Username</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Join Date</th>
            <td>{{ user.date_joined }}</td>
        </tr>
    </table>
    <a href="{% url 'profile_edit' %}" class="btn btn-primary"><i class="glyphicon glyphicon-pencil"></i> Edit</a>
    <a href="{% url 'auth_password_change' %}" class="btn btn-primary"><i class="glyphicon glyphicon-lock"></i> Change Password</a>
{% endblock %}

blog/accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}

{% block title %}
    Profile Edit | {{ block.super }}
{% endblock %}

{% block header %}
    Profile Edit
{% endblock %}

{% block content %}
    {% load bootstrap3 %}

    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-success" type="submit"><i class="glyphicon glyphicon-floppy-disk"></i> Save</button>
            <a class="btn btn-primary" href="{% url 'profile' %}"><i class="glyphicon glyphicon-arrow-left"></i> Back</a>
        {% endbuttons %}
    </form>
{% endblock %}

blog/posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Home | {{ block.super }}
{% endblock %}

{% block header %}
    Posts
{% endblock %}

{% block content %}
    {% if posts %}
        {% for post in posts %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>{{ post.title }}</h3>
                </div>

                <div class="panel-body">
                    <p>{{ post.text }}</p>
                </div>

                <div class="panel-footer">
                    <p>@{{ post.user }} on {{ post.creation_date }}</p>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>No posts yet, sorry bro =(</p>
    {% endif %}
{% endblock %}

blog/posts/templates/posts/new.html
{% extends 'base.html' %}

{% block title %}
    New Post | {{ block.super }}
{% endblock %}

{% block header %}
    New Post
{% endblock %}

{% block content %}
    {% load bootstrap3 %}
    
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-success" type="submit"><i class="glyphicon glyphicon-floppy-disk"></i> Save</button>
            <a class="btn btn-primary" href="{% url 'posts:index' %}"><i class="glyphicon glyphicon-arrow-left"></i> Back</a>
        {% endbuttons %}
    </form>
{% endblock %}

blog/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <title>
        {% block title %}
            Group 123 Blog
        {% endblock %}
    </title>

    <link rel="icon" href="{% static "img/favicon.png" %}">

    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/style.css" %}" rel="stylesheet">
</head>

<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'posts:index' %}">Blog - Group 123</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">

                <!-- all posts -->
                <li>
                    <a href="{% url 'posts:index' %}">All Posts</a>
                </li>

                {% if user.is_authenticated %}

                    <!-- new post -->
                    <li>
                        <a href="{% url 'posts:new' %}">New Posts</a>
                    </li>

                    <!-- account -->
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" role="button" class="dropdown-toggle">
                            {{ user.username }}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">

                            <!-- profile -->
                            <li>
                                <a href="{% url 'profile' %}">Profile</a>
                            </li>

                            <!-- logout -->
                            <li>
                                <a href="{% url 'auth_logout' %}">Logout</a>
                            </li>
                        </ul>
                    </li>
                {% else %}

                    <!-- signup -->
                    <li>
                        <a href="{% url 'registration_register' %}">Sign Up</a>
                    </li>

                    <!-- login -->
                    <li>
                        <a href="{% url 'auth_login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div id="wrap">
    <section id="main" class="container">

        <h1 class="page-header">
            {% block header %}
            {% endblock %}
        </h1>

        <!-- templates here -->
        {% block content %}
        {% endblock %}

    </section>
</div>

<footer class="footer">
    <div class="container">
        <p>Group 123 -
            <a href="https://github.com/WebTech2-Group123/django-assignment" target="_blank">
                https://github.com/WebTech2-Group123/django-assignment
            </a>
        </p>
    </div>
</footer>

<script src="{% static "js/jquery-2.1.4.min.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>

</body>

</html>